spring.application.name=personas
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/db_personas
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
